npmPublishAccess: public
initScope: hashicorp
initFields:
  license: MPL-2.0
  version: 0.0.1
  author: FIXME
  repository:
    type: git
    url: "git+https://github.com/hashicorp/structure.git"
  bugs:
    url: "https://github.com/hashicorp/structure/issues"
  homepage: "https://github.com/hashicorp/structure#readme"
  publishConfig:
    access: public
